### ISSUE TITLE
Levantar o capital humano do projeto

### ISSUE THREAD

**Issue by brunoruas2** [brunoruas2/brick-by-brick#3]

**Comment by brunoruas2** [comment]
- [x]  Bruno Ruas
 - [x]  Leonardo Oliveira
 - [x]  ⁠Antonio Cícero
 - [ ]  Vitor Macedo
 - [ ]  Jonas Amaro
 - [ ]  João Victor
 - [ ]  Murilo Conceição
 - [ ]  Matheus Assis
 - [x]  Luís Miguel
 - [ ]  Dalton C. Guimarães
 - [ ]  Kelli Souza

**Comment by brunoruas2** [comment]
Nome: Bruno Ruas
Github: https://github.com/brunoruas2

Eu comecei a programar em 2017 usando R pra trabalhos RPA (Robot Process Automations) depois comecei com python quando fui fazer web scraping (na época o RSelenium tava engatinhando).

Em 2022 iniciei um tecnólogo de Análise e Desenvolvimento de Sistemas pra aprender a desenvolver software de maneira mais profissional.

Eu trabalho como desenvolvedor backend na GFT Tech. Também faço freela pra 2 clientes.

Linguagens: C#, Python, JS e PHP
Frameworks: .NET, Django, Flask, Laravel

Projetos:
Meu site de estudos -> https://brunoruas2.github.io/CC_site/nav/PUC/Sobre/puc/
Projeto Matemática -> https://economiamainstream.com.br/artigo/matematica/
Lib pra R -> https://github.com/brunoruas2/gujarati
Coletor de dados para DFP -> https://github.com/brunoruas2/informacoes_trimestrais_b3

**Comment by azmovi** [comment]
Nome: Antonio Cícero Azevedo
Github: https://github.com/azmovi

Eu comecei a programar de fato no final de 2022 quando eu passei para computação na Ufscar (to no 5 período de 8), todo meu conhecimento de python vem por conta de um cara foda que faz lives para o [@dunossauro](https://github.com/dunossauro), e to aprendendo bastante desde de então graças a ele.

Sou estudante, nunca cheguei a trabalhar de fato com programação ainda, mas atualmente estou desenvolvendo uma iniciação cientifica com a faculdade que implementa o algortimo k-means usando o algoritmo de Dijkstra. Proximo ano eu foco em pegar um estagio e fé com fé (muito provalvemente em uma startup)

Na faculdade faço parte do grupo de extensão de ciencia de dados [panda](https://www.instagram.com/pandaufscar/)
Tabém faço parte do grupo de extensão que organiza a Semana da Computação na Ufscar a [secomp](https://www.secompufscar.com.br/)

Linguagens: C++, python
Frameworks: [FastAPI](https://github.com/tiangolo/fastapi) (aprendendo)

Principais Projetos:
[K-Means Topológico (IC)](https://github.com/azmovi/geo-k-means)
[Analise de dados em jogos](https://github.com/azmovi/analise-dados-videogame)
[IA que resolve o wordle](https://github.com/azmovi/wordle-ia)
[Auxiliador para contar cartas no BlackJack](https://github.com/azmovi/BlackJack)

**Comment by luismiguelcelka** [comment]
Nome: Luís Miguel 

Não tenho muito o que falar no resumo, pois não tenho nenhuma experiência com programação, mas tô com tempo e tenho muita vontade de aprender.

Meu primeiro contato com programação foi em 2021, fiz metade de um curso de R aplicado à Macroeconomia da galera do Análise Macro. E tive um breve contato com Python pelos vídeos do Guanabara, que, inclusive, voltei a ver ontem pelo projeto aí e também vou iniciar o curso que mandaram de GitHub 

Fiz 3 semestres de Estatística e atualmente tô fazendo algo nada a ver com programação (Direito kkk)

Se eu não for atrapalhar, vou ficar feliz em participar (mesmo que minimamente) e aprender aí com vcs

**Comment by leovnoliveira** [comment]
Nome: Leonardo Oliveira
GitHub: https://github.com/leovnoliveira

Sou economista e comecei a programar ano passado, por meio do curso de R do @⁨Baruque⁩ inclusive. Mais além em 2023 comecei a trabalhar num escritório de contabilidade digital na parte fiscal. A vontade de voltar a programar foi para automatizar minha rotina de tarefas e auxiliar a gestão na criação de dashboards e relatórios gerenciais para tomada de decisão. Entao comecei a investir em cursos e estudar Python e R de maneira consistente e séria.

Comecei com os cursos de Análise de Demonstartivos Financeiros no R e Modelagem e Previsão da Análise Macro, donde criei meu primeiro projeto, um panel de dados contábeis e indicadores financeiros das empresas da bolsa, seguindo toda a etapa do ciclo de análise de dados, desde a coleta dos dados (usando pacotes prontos do R) até o deploy do projeto. Depois conheci o código.py, que é um curso de Python aplicado para finanças e mercado financeiro, por meio de um colega, e achei um fitch legal para focar, somando com meu interesse por economia e o alto ROI dessa área, então estou fazendo essa formação tmb. 
Dado tudo isso, meu conhecimento de python está acumulando e crescendo, donde, para análise de dados, aprendi na prática que dominar e saber usar bem o Pandas já é quase todo o trabalho "braçal" garantido, sendo parte importante do ciclo de análise de dados.

Linguagens:
R
Python 

Projeto: https://leovnoliveira.shinyapps.io/dashsdabolsa/

Análises de Machine Learning:

Fluxo de Análise de Dados para um modelo preditivo do PIB do Brasil: https://colab.research.google.com/drive/1XMzaMa50HDtX4YVFoEzpxpiYNihSDbv4?usp=sharing

Modelo preditivo de inflação do Brasil com dados mensais do IPCA: método de previsão SARIMA
https://colab.research.google.com/drive/1B5FmnovpScqQQiVfznkK9WbuOPRJXHS8?usp=sharing

Classificando economias em avançadas e não avançadas por meio de Regressão Logísticas com dados do FMI https://colab.research.google.com/drive/1v7Ld-GgpRBvJzMNDNyulKQW1DmUY3r-v?usp=sharing

**Comment by brunoruas2** [comment]
Vou manter a issue fechada porque já temos um quórum aceitável. Mas podem ir lançando aqui seus resumos!
